# Generated by ChatGPT for Django 5.0.4
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=200)),
                ('expiry', models.CharField(max_length=50)),
                ('qty', models.IntegerField(default=0)),
                ('refill_line', models.IntegerField(default=0)),
                ('alert', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'unique_together': {('item', 'expiry')},
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('okazu', models.CharField(max_length=200)),
                ('okazu_expiry', models.CharField(max_length=50)),
                ('gohan', models.CharField(max_length=50)),
                ('gohan_expiry', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed', models.BooleanField(default=False)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled', models.BooleanField(default=False)),
            ],
        ),
    ]
